@url_dev=http://localhost:3055/v1/api

### Gửi tin nhắn mới (text hoặc có file)
POST {{url_dev}}/messages
Content-Type: application/json
x-client-id:67fc8f626ba178060c6b91e6
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZjOGY2MjZiYTE3ODA2MGM2YjkxZTYiLCJwaG9uZSI6IjA5NDI3MjAzMjkiLCJpYXQiOjE3NDQ4NjM2MjcsImV4cCI6MTc0NTAzNjQyN30.tRgRzbMnIhj0UDg356cCRToWe9ZGOX7MfaBL8Mm_V3Y

{
    "conversation_id": "67fc8f626ba178060c6b91e7",
    "content": "Are you ok!"
}

### Lấy danh sách tin nhắn
GET {{url_dev}}/conversations/67fc8f626ba178060c6b91e7/messages?page=1&limit=10
Content-Type: application/json
x-client-id:67fc8f626ba178060c6b91e6
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZjOGY2MjZiYTE3ODA2MGM2YjkxZTYiLCJwaG9uZSI6IjA5NDI3MjAzMjkiLCJpYXQiOjE3NDQ4NjM2MjcsImV4cCI6MTc0NTAzNjQyN30.tRgRzbMnIhj0UDg356cCRToWe9ZGOX7MfaBL8Mm_V3Y

### Thu hồi tin nhắn
PUT {{url_dev}}/messages/67ff89d3315b0822c17d1212/revoke
Content-Type: application/json
x-client-id:67ff6544b864082a861acd8e
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZmNjU0NGI4NjQwODJhODYxYWNkOGUiLCJwaG9uZSI6IjA1NTk0MjEzOTYiLCJ0b2tlblZlcnNpb24iOjEsImlhdCI6MTc0NDc5MTc3OSwiZXhwIjoxNzQ0OTY0NTc5fQ.Ju26zLIautA6vfVd9dqMrQisBra-1_XIxrT5324cK0M

### Xoá tin nhắn
PUT {{url_dev}}/messages/680905d225ecac4e1c48cffe/delete
Content-Type: application/json
x-client-id:67ff6544b864082a861acd8e
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZmNjU0NGI4NjQwODJhODYxYWNkOGUiLCJwaG9uZSI6IjA1NTk0MjEzOTYiLCJ0b2tlblZlcnNpb24iOjEsImlhdCI6MTc0NTM0MDkxMCwiZXhwIjoxNzQ1NTEzNzEwfQ.83mi83Bo_XYOc5PAFx9U_iW4k-NDkoZpEUSvIfKnmOw

### Chuyển tiếp tin nhắn
POST {{url_dev}}/messages/forward
Content-Type: application/json
x-client-id:67ff6544b864082a861acd8e
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZmNjU0NGI4NjQwODJhODYxYWNkOGUiLCJwaG9uZSI6IjA1NTk0MjEzOTYiLCJ0b2tlblZlcnNpb24iOjEsImlhdCI6MTc0NDc5MTc3OSwiZXhwIjoxNzQ0OTY0NTc5fQ.Ju26zLIautA6vfVd9dqMrQisBra-1_XIxrT5324cK0M

{
    "message_id": "67fc8f626ba178060c6b91e8",
    "target_conversion_id": "67ff6fb4a23366e8b5d4aafc"
}

### Đánh dấu tin nhắn đã đọc
PUT {{url_dev}}/messages/mark-as-read
Content-Type: application/json
x-client-id:67ff6544b864082a861acd8e
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2ZmNjU0NGI4NjQwODJhODYxYWNkOGUiLCJwaG9uZSI6IjA1NTk0MjEzOTYiLCJ0b2tlblZlcnNpb24iOjEsImlhdCI6MTc0NDc5MTc3OSwiZXhwIjoxNzQ0OTY0NTc5fQ.Ju26zLIautA6vfVd9dqMrQisBra-1_XIxrT5324cK0M

{
    "conversation_id": "67ff6fb4a23366e8b5d4aafc"
}

### Add Reaction to Message
POST {{url_dev}}/messages/reaction
Content-Type: application/json
x-client-id:6801ce58f92ca12177596d90
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAxY2U1OGY5MmNhMTIxNzc1OTZkOTAiLCJwaG9uZSI6IjA5NDI3MjAzMjkiLCJ0b2tlblZlcnNpb24iOjEsImlhdCI6MTc0NTI1MzQzNywiZXhwIjoxNzQ1NDI2MjM3fQ.NyB--NiWUQXGANtC-cBT5vKpbdsMPLY4NOsY1pWugN4

{
    "message_id": "6809101bc419efb29519af2f",
    "emoji": ":heart"
}

### Remove Reaction from Message
DELETE {{url_dev}}/messages/reaction
Content-Type: application/json
x-client-id:6801ce58f92ca12177596d90
authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAxY2U1OGY5MmNhMTIxNzc1OTZkOTAiLCJwaG9uZSI6IjA5NDI3MjAzMjkiLCJ0b2tlblZlcnNpb24iOjEsImlhdCI6MTc0NTI1MzQzNywiZXhwIjoxNzQ1NDI2MjM3fQ.NyB--NiWUQXGANtC-cBT5vKpbdsMPLY4NOsY1pWugN4

{
    "message_id": "6809101bc419efb29519af2f"
}